name: Android APK Builder

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Optional Gradle module to assemble (e.g., app)"
        required: false
        default: ""
  push:
    branches: [ main, master ]
    paths:
      - "**.zip"
      - ".github/workflows/android-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find and extract app ZIP
        id: unzip
        shell: bash
        run: |
          set -e
          shopt -s nullglob
          zips=(./*.zip ./zips/*.zip)
          if (( ${#zips[@]} )); then
            echo "Found ZIP: ${zips[0]}"
            mkdir -p source
            unzip -q "${zips[0]}" -d source
            entries=(source/*)
            if [ ${#entries[@]} -eq 1 ] && [ -d "${entries[0]}" ]; then
              mv "${entries[0]}" project && rmdir source
            else
              mv source project
            fi
            echo "project_dir=project" >> "$GITHUB_OUTPUT"
          else
            echo "No ZIP found; using repo root."
            echo "project_dir=." >> "$GITHUB_OUTPUT"
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
