name: Android APK Builder

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Optional Gradle module to assemble (e.g., app)"
        required: false
        default: ""
  push:
    branches: [ main, master ]
    paths:
      - "**.zip"
      - ".github/workflows/android-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find and extract app ZIP
        id: unzip
        shell: bash
        run: |
          set -e
          shopt -s nullglob
          zips=(./*.zip ./zips/*.zip)
          if (( ${#zips[@]} )); then
            echo "Found ZIP: ${zips[0]}"
            mkdir -p source
            unzip -q "${zips[0]}" -d source
            entries=(source/*)
            if [ ${#entries[@]} -eq 1 ] && [ -d "${entries[0]}" ]; then
              mv "${entries[0]}" project && rmdir source
            else
              mv source project
            fi
            echo "project_dir=project" >> "$GITHUB_OUTPUT"
          else
            echo "No ZIP found; using repo root."
            echo "project_dir=." >> "$GITHUB_OUTPUT"
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          distribution: "commandlinetools"

      - name: Accept licenses & install SDK 34 + build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Generate Gradle wrapper if missing (8.7)
        id: gradle
        shell: bash
        run: |
          set -e
          ROOT="${{ steps.unzip.outputs.project_dir }}"
          WRAPPER=$(find "$ROOT" -maxdepth 3 -name gradlew -type f | head -n 1 || true)
          if [ -z "$WRAPPER" ]; then
            echo "No gradlew found. Installing Gradle and generating wrapper..."
            sudo apt-get update -y
            sudo apt-get install -y gradle
            (cd "$ROOT" && gradle wrapper --gradle-version 8.7 --distribution-type all)
            WRAPPER=$(find "$ROOT" -maxdepth 3 -name gradlew -type f | head -n 1)
          fi
          chmod +x "$WRAPPER"
          echo "wrapper=$WRAPPER" >> "$GITHUB_OUTPUT"
          echo "project_root=$(dirname "$WRAPPER")" >> "$GITHUB_OUTPUT"

      - name: Show Java/Gradle versions
        working-directory: ${{ steps.gradle.outputs.project_root }}
        run: |
          java -version || true
          ./gradlew --version || true

      - name: Enable Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build Debug APK (verbose)
        working-directory: ${{ steps.gradle.outputs.project_root }}
        run: |
          set -e
          if [ -n "${{ github.event.inputs.module }}" ]; then
            ./gradlew ${{ github.event.inputs.module }}:assembleDebug --stacktrace --info --no-daemon
          else
            ./gradlew assembleDebug --stacktrace --info --no-daemon
          fi

      - name: Collect build outputs
        id: collect
        working-directory: ${{ steps.gradle.outputs.project_root }}
        shell: bash
        run: |
          set -e
          mkdir -p "$GITHUB_WORKSPACE/artifacts" "$GITHUB_WORKSPACE/reports"
          find . -type f \( -name "*.apk" -o -name "*.aab" \) -print0 | xargs -0 -I{} cp "{}" "$GITHUB_WORKSPACE/artifacts/" || true
          find . -type d -path "*/build/reports" -exec cp -r {} "$GITHUB_WORKSPACE/reports/" \; || true
          count=$(ls -1 "$GITHUB_WORKSPACE/artifacts" 2>/dev/null | wc -l | xargs)
          echo "found=$count" >> "$GITHUB_OUTPUT"

      - name: Upload APK/AAB artifacts
        if: steps.collect.outputs.found != '0'
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.sha }}
          path: artifacts
          if-no-files-found: error
          retention-days: 30

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.sha }}
          path: reports
          if-no-files-found: ignore
          retention-days: 14
